src/eis/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import forms, views

urlpatterns = [
    url(r'^login/$', auth_views.login, {'template_name':'users/login.html','authentication_form':forms.AppLogin}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name':'home.html'}, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^create/$', views.create_user, name='create'),
    url(r'^list/$', views.list_users, name='list'),
    url(r'^roles/$', views.create_role, name='roles'),
]

src/users/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

# Model for User profile
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.IntegerField(default=0)

    # RegEx
    phone_regex = RegexValidator(regex=r'^(?:\+?63)?[09]\d{9,12}$', message="Format: '+639999999999, 09999999999, 0744449999'. Up to 13 digits allowed.")
    num_regex = RegexValidator(regex=r'[0-9]', message="Numbers are only, up to 12 digits allowed.")

    # Personal Info
    first_name = models.CharField(max_length=64)
    middle_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    gender = models.CharField(max_length=6, null=True)
    birthdate = models.DateField()
    civil_status = models.CharField(max_length=64, null=True)
    tel_no = models.CharField(validators=[phone_regex], max_length=12, blank=True)
    mobile_no = models.CharField(validators=[phone_regex], max_length=12, blank=True)
    address = models.TextField(blank=True, null=True)
    religion = models.CharField(max_length=64, null=True)
    nationality = models.CharField(max_length=64, null=True)

    # Bank Account
    bank_name = models.CharField(max_length=64, blank=True)
    bank_no = models.IntegerField(blank=True, null=True)

    # Salary and Allowance
    basic_salary = models.DecimalField(max_digits=11, decimal_places=2, null=True);
    monthly_allowance = models.DecimalField(max_digits=11, decimal_places=2, null=True);

    # Contribution Details
    tin_no = models.CharField(validators=[num_regex], max_length=12, blank=True)
    sss_no = models.CharField(validators=[num_regex], max_length=10, blank=True)
    gsis_no = models.CharField(validators=[num_regex], max_length=12, blank=True)
    pagibig_no = models.CharField(validators=[num_regex], max_length=12, blank=True)
    philhealth_no = models.CharField(validators=[num_regex], max_length=12, blank=True)

    tin_contribution = models.DecimalField(max_digits=11, decimal_places=2, null=True);
    sss_contribution = models.DecimalField(max_digits=11, decimal_places=2, null=True);
    gsis_contribution = models.DecimalField(max_digits=11, decimal_places=2, null=True);
    pagibig_contribution = models.DecimalField(max_digits=11, decimal_places=2, null=True);
    philhealth_contribution = models.DecimalField(max_digits=11, decimal_places=2, null=True);

    # Employment Info
    position = models.IntegerField(default=0, blank=True)
    department = models.IntegerField(default=0, blank=True)
    entry_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)

    # Modification log
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

# Model for User Roles
class Role(models.Model):
    code = models.CharField(max_length=64, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.code

    def __int__(self):
        return self.id

# Model for User Postion
class Position(models.Model):
    position = models.CharField(max_length=64, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.position

    def __int__(self):
        return self.id

# Model for User Department
class Department(models.Model):
    department = models.CharField(max_length=64, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now=False, auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.department

    def __int__(self):
        return self.id

src/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput, Select
from django.contrib.auth.models import User
from .models import Profile, Role, Position, Department

class AppLogin(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))

class UserForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=PasswordInput(attrs={'class':'form-control','placeholder':'Confirm Password'}))
    class Meta:
        model = User
        fields = ['username','password']
        widgets = {
            'username': TextInput(attrs={'class':'form-control','placeholder':'Username'}),
            'password': PasswordInput(attrs={'class':'form-control','placeholder':'Password'}),
        }
    def clean_confirm_password(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')
        if not password2:
            raise forms.ValidationError("You must confirm your password")
        if password1 != password2:
            raise forms.ValidationError("Your passwords do not match")
        return password2

class ProfileForm(forms.ModelForm):
    role = forms.ModelChoiceField(queryset=Role.objects.all(), empty_label="(-Select Role-)", widget=Select(attrs={'class':'form-control'}))
    position = forms.ModelChoiceField(queryset=Position.objects.all(), empty_label="(-Select Position-)", widget=Select(attrs={'class':'form-control'}))
    department = forms.ModelChoiceField(queryset=Department.objects.all(), empty_label="(-Select Department-)", widget=Select(attrs={'class':'form-control'}))
    gender_choices = (
        ('male', 'Male'),
        ('female', 'Female'),
    )
    civil_status_choices = (
        ('single', 'Single'),
        ('married', 'Married'),
        ('widowed', 'Widowed'),
    )
    gender = forms.ChoiceField(choices=gender_choices, widget=Select(attrs={'class':'form-control'}))
    civil_status = forms.ChoiceField(choices=civil_status_choices, widget=Select(attrs={'class':'form-control'}))
    class Meta:
        model = Profile
        exclude = ['user','created_at','updated_at']
        widgets = {
            'first_name': TextInput(attrs={'placeholder':'First name','class':'form-control'}),
            'middle_name': TextInput(attrs={'placeholder':'Middle name','class':'form-control'}),
            'last_name': TextInput(attrs={'placeholder':'Last name','class':'form-control'}),
            'birthdate': TextInput(attrs={'placeholder':'Birthdate','class':'form-control'}),
            'tel_no': TextInput(attrs={'placeholder':'Telephone Number','class':'form-control'}),
            'mobile_no': TextInput(attrs={'placeholder':'Mobile Number','class':'form-control'}),
            'address': TextInput(attrs={'placeholder':'Address','class':'form-control'}),
            'religion': TextInput(attrs={'placeholder':'Religion','class':'form-control'}),
            'nationality': TextInput(attrs={'placeholder':'Nationality','class':'form-control'}),
            'bank_name': TextInput(attrs={'placeholder':'Bank Name','class':'form-control'}),
            'bank_no': TextInput(attrs={'placeholder':'Bank Acct No.','class':'form-control'}),
            'basic_salary': TextInput(attrs={'placeholder':'Basic Salary','class':'form-control'}),
            'monthly_allowance': TextInput(attrs={'placeholder':'Monthly Allowance','class':'form-control'}),
            'tin_no': TextInput(attrs={'placeholder':'TIN No.','class':'form-control'}),
            'sss_no': TextInput(attrs={'placeholder':'SSS No.','class':'form-control'}),
            'gsis_no': TextInput(attrs={'placeholder':'GSIS No.','class':'form-control'}),
            'pagibig_no': TextInput(attrs={'placeholder':'PagIbig No.','class':'form-control'}),
            'philhealth_no': TextInput(attrs={'placeholder':'PhilHealth No.','class':'form-control'}),
            'entry_date': TextInput(attrs={'placeholder':'Entry date','class':'form-control'}),
            'end_date': TextInput(attrs={'placeholder':'End date','class':'form-control'}),
        }

class RoleForm(forms.ModelForm):
    class Meta:
        model = Role
        exclude = ['created_at','updated_at']
        widgets = {
            'code': TextInput(attrs={'placeholder':'Code','class':'form-control'}),
            'description': TextInput(attrs={'placeholder':'Description','class':'form-control'}),
        }

src/users/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import UserForm, ProfileForm, RoleForm
from .role import role_required
from .models import Profile

@login_required
def profile(request):
    context = {}
    return render(request, 'users/profile.html', context)

@role_required(2)
def create_user(request):
    user_form = UserForm(request.POST or None)
    user_profile_form = ProfileForm(request.POST or None)

    if request.method == 'POST':
        if user_form.is_valid() and user_profile_form.is_valid():
            user_form.is_superuser = False
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            userprofile = user_profile_form.save(commit=False)
            userprofile.user = user
            userprofile.save()
            messages.success(request, 'User Successfully Created.')
            return redirect('users:create');

    context = {
        'user_form': user_form,
        'user_profile_form': user_profile_form,
    }

    return render(request, 'users/create_user.html', context)

@role_required(2)
def create_role(request):
    role_form = RoleForm(request.POST or None)

    if request.method == 'POST':
        if role_form.is_valid():
            role_form.save()
            messages.success(request, 'Role Successfully Created.')
            return redirect('users:roles');

    context = {
        'role_form':role_form
    }
    
    return render(request, 'users/create_role.html', context)

@role_required(2)
def list_users(request):
    queryset_list = Profile.objects.all()
    context = {
        'employees': queryset_list
    }
    return render(request, 'users/list_users.html', context)

src/templates/users/create_role.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <p></p>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.level_tag }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Create Role</h3>
            </div>
            <div class="panel-body">

                <form method="post" action="{% url 'users:roles' %}" class="form-horizontal">

                    {% csrf_token %}

                    <input type="hidden" name="next" value="{{ next }}" />
                    
                    <div class="form-group{% if role_form.code.errors %} has-error{% else %}{% endif %}">
                        <label class="col-md-3 control-label">Code :</label>
                        <div class="col-md-8">
                            {{ role_form.code }}
                            {{ role_form.code.errors.as_text }}
                        </div>
                    </div>

                    <div class="form-group{% if role_form.description.errors %} has-error{% else %}{% endif %}">
                        <label class="col-md-3 control-label">Description :</label>
                        <div class="col-md-8">
                            {{ role_form.description }}
                            {{ role_form.description.errors.as_text }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-8">
                            <button type="submit" name="login" class="btn btn-primary">Create</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock content %}

src/templates/users/create_user.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-8 col-md-offset-2">
        <p></p>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.level_tag }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <form method="post" action="{% url 'users:create' %}" class="form-horizontal">

            {% csrf_token %}
            
            <input type="hidden" name="next" value="{{ next }}" />

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Login Details</h3>
                </div>
            </div>
            <div class="form-group{% if user_form.username.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Username :</label>
                <div class="col-md-8">
                    {{ user_form.username }}
                    {{ user_form.username.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_form.password.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Password :</label>
                <div class="col-md-8">
                    {{ user_form.password }}
                    {{ user_form.password.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_form.confirm_password.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Confirm Password :</label>
                <div class="col-md-8">
                    {{ user_form.confirm_password }}
                    {{ user_form.confirm_password.errors.as_text }}
                </div>
            </div>

            <div class="form-group{% if user_profile_form.role.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Role :</label>
                <div class="col-md-8">
                    {{ user_profile_form.role }}
                    {{ user_profile_form.role.errors.as_text }}
                </div>
            </div>
            
            <p>&nbsp;</p>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Personal Info</h3>
                </div>
            </div>
            <div class="form-group{% if user_profile_form.first_name.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">First Name :</label>
                <div class="col-md-8">
                    {{ user_profile_form.first_name }}
                    {{ user_profile_form.first_name.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.middle_name.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Middle Name :</label>
                <div class="col-md-8">
                    {{ user_profile_form.middle_name }}
                    {{ user_profile_form.middle_name.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.last_name.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Last Name :</label>
                <div class="col-md-8">
                    {{ user_profile_form.last_name }}
                    {{ user_profile_form.last_name.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.gender.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Gender :</label>
                <div class="col-md-8">
                    {{ user_profile_form.gender }}
                    {{ user_profile_form.gender.errors.as_text }}
                </div>
            </div>            
            <div class="form-group{% if user_profile_form.birthdate.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Birth Date :</label>
                <div class="col-md-8">
                    {{ user_profile_form.birthdate }}
                    {{ user_profile_form.birthdate.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.civil_status.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Civil Status :</label>
                <div class="col-md-8">
                    {{ user_profile_form.civil_status }}
                    {{ user_profile_form.civil_status.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.tel_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Telephone No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.tel_no }}
                    {{ user_profile_form.tel_no.errors.as_text }}
                </div>
            </div> 
            <div class="form-group{% if user_profile_form.mobile_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Mobile No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.mobile_no }}
                    {{ user_profile_form.mobile_no.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.address.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Address :</label>
                <div class="col-md-8">
                    {{ user_profile_form.address }}
                    {{ user_profile_form.address.errors.as_text }}
                </div>
            </div> 
            <div class="form-group{% if user_profile_form.religion.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Religion :</label>
                <div class="col-md-8">
                    {{ user_profile_form.religion }}
                    {{ user_profile_form.religion.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.nationality.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Nationality :</label>
                <div class="col-md-8">
                    {{ user_profile_form.nationality }}
                    {{ user_profile_form.nationality.errors.as_text }}
                </div>
            </div>

            <p>&nbsp;</p>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Bank Account</h3>
                </div>
            </div>
            <div class="form-group{% if user_profile_form.bank_name.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Bank Name :</label>
                <div class="col-md-8">
                    {{ user_profile_form.bank_name }}
                    {{ user_profile_form.bank_name.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.bank_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Bank Acct. No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.bank_no }}
                    {{ user_profile_form.bank_no.errors.as_text }}
                </div>
            </div>
            
            <p>&nbsp;</p>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Salary and Allowance</h3>
                </div>
            </div>
            <div class="form-group{% if user_profile_form.basic_salary.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Basic Salary :</label>
                <div class="col-md-8">
                    {{ user_profile_form.basic_salary }}
                    {{ user_profile_form.basic_salary.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.monthly_allowance.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Monthly Allowance :</label>
                <div class="col-md-8">
                    {{ user_profile_form.monthly_allowance }}
                    {{ user_profile_form.monthly_allowance.errors.as_text }}
                </div>
            </div>
            
            <p>&nbsp;</p>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Contributions and Deductions</h3>
                </div>
            </div>
            <div class="form-group{% if user_profile_form.tin_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">TIN No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.tin_no }}
                    {{ user_profile_form.tin_no.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.sss_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">SSS No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.sss_no }}
                    {{ user_profile_form.sss_no.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.gsis_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">GSIS No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.gsis_no }}
                    {{ user_profile_form.gsis_no.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.pagibig_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">PagIbig No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.pagibig_no }}
                    {{ user_profile_form.pagibig_no.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.philhealth_no.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">PhilHealth No. :</label>
                <div class="col-md-8">
                    {{ user_profile_form.philhealth_no }}
                    {{ user_profile_form.philhealth_no.errors.as_text }}
                </div>
            </div>

            <p>&nbsp;</p>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Employment Information</h3>
                </div>
            </div>
            <div class="form-group{% if user_profile_form.position.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Position :</label>
                <div class="col-md-8">
                    {{ user_profile_form.position }}
                    {{ user_profile_form.position.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.department.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Department :</label>
                <div class="col-md-8">
                    {{ user_profile_form.department }}
                    {{ user_profile_form.department.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.entry_date.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">Entry Date :</label>
                <div class="col-md-8">
                    {{ user_profile_form.entry_date }}
                    {{ user_profile_form.entry_date.errors.as_text }}
                </div>
            </div>
            <div class="form-group{% if user_profile_form.end_date.errors %} has-error{% else %}{% endif %}">
                <label class="col-md-3 control-label">End Date :</label>
                <div class="col-md-8">
                    {{ user_profile_form.end_date }}
                    {{ user_profile_form.end_date.errors.as_text }}
                </div>
            </div>

            <p>&nbsp;</p>

            <div class="footer navbar-fixed-bottom">
                <div class="container">
                    <div class="col-md-12">
                        <div class="col-md-8 col-md-offset-2 text-right form-tool-controls">
                            <p></p>
                            <button type="submit" name="login" class="btn btn-primary">Submit Form</button>
                            <p></p>
                        </div>
                    </div>
                </div>
            </div>

        </form><!-- /.form-horizontal -->

    </div><!-- /.col-md-8 -->
{% endblock content %}

src/templates/users/list_users.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-12">
        <p></p>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Employee List</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Department</th>
                            <th>Postion</th>
                            <th>Entry Date</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for obj in employees %}
                            <tr>
                                <td>{{ obj.last_name }}, {{ obj.first_name }}</td>
                                <td>{{ obj.department }}</td>
                                <td>{{ obj.position }}</td>
                                <td>{{ obj.entry_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div><!-- /.panel -->
    </div><!-- /.col-md-12 -->
{% endblock content %}

src/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-md-6 col-md-offset-3">
        <p></p>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Login</h3>
            </div>
            <div class="panel-body">
                <form method="post" action="{% url 'users:login' %}" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username" class="col-md-3 control-label">Username :</label>
                        <div class="col-md-8">
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_password" class="col-md-3 control-label">Password :</label>
                        <div class="col-md-8">
                            {{ form.password }}
                        </div>
                    </div>
                    <input type="hidden" name="next" value="{{ next }}" />
                    <div class="form-group">
                        <label for="id_username" class="col-md-3 control-label"></label>
                        <div class="col-md-8">
                            <button type="submit" name="login" class="btn btn-primary">Login</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        {% if form.errors %}
            <div class="alert alert-danger">
                <p>Your username and password didn't match, please try again.</p>
            </div>
        {% endif %}
    </div>
{% endblock content %}

src/templates/users/profile.html
{% extends "base.html" %}

{% block content %}
    <h1>Profile</h1>
{% endblock content %}